services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=your_openai_api_key
    volumes:
      - ./backend/tracks:/app/tracks

  frontend:
    build: ./frontend
    ports:
      - "5174:5173"
    depends_on:
      - backend
